const data = {
  pilots: [
    {
      name: 'Nino Farina',
      country: 'Italia',
      years: [1950],
      img: 'https://upload.wikimedia.org/wikipedia/commons/f/fc/NinoFarina.jpg',
    },
    {
      name: 'Juan Manuel Fangio',
      country: 'Argentina',
      years: [1951, 1954, 1955, 1956, 1957],
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Fangio.png/322px-Fangio.png',
    },
    {
      name: 'Mike Hawthorn',
      country: 'Reino Unido',
      years: [1958],
      img: 'https://upload.wikimedia.org/wikipedia/commons/2/2a/Mike_Hawthorn%2C_autocoureur_verongelukt%2C_Bestanddeelnr_910-1117.jpg',
    },
    {
      name: 'Alberto Ascari',
      country: 'Italia',
      years: [1952, 1953],
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Ascari_last_photo_in_car.jpg/312px-Ascari_last_photo_in_car.jpg',
    },
    {
      name: 'Jack Brabham',
      country: 'Australia',
      years: [1959, 1960, 1966],
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/BrabhamJack1966B.jpg/340px-BrabhamJack1966B.jpg',
    },
    {
      name: 'Phil Hill',
      country: 'Estados Unidos',
      years: [1961],
      img: 'https://upload.wikimedia.org/wikipedia/commons/9/9f/-Phil_Hill_1991_cropped.jpg',
    },
    {
      name: 'Graham Hill',
      country: 'Reino Unido',
      years: [1962, 1968],
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/HillGraham1969Aug.jpg/315px-HillGraham1969Aug.jpg',
    },
    {
      name: 'Jim Clark',
      country: 'Reino Unido',
      years: [1963, 1965],
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Jim_Clark.jpg/310px-Jim_Clark.jpg',
    },
    {
      name: 'John Surtees',
      country: 'Reino Unido',
      years: [1964],
      img: 'https://upload.wikimedia.org/wikipedia/commons/c/c3/John_Surtees.JPG',
    },
    {
      name: 'Denny Hulme',
      country: 'Australia',
      years: [1967],
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Hulme_seitenrichtig.jpg/291px-Hulme_seitenrichtig.jpg',
    },
    {
      name: 'Jackie Stewart',
      country: 'Reino Unido',
      years: [1969, 1971, 1973],
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Jackie_Stewart_2011_British_Grand_Prix.jpg/354px-Jackie_Stewart_2011_British_Grand_Prix.jpg',
    },
    {
      name: 'Jochen Rindt',
      country: 'Austria',
      years: [1970],
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Rindt_at_1970_Dutch_Grand_Prix_%282B%29.jpg/365px-Rindt_at_1970_Dutch_Grand_Prix_%282B%29.jpg',
    },
    {
      name: 'Emerson Fittipaldi',
      country: 'Brasil',
      years: [1972, 1974],
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Emerson_Fittipaldi.jpg/320px-Emerson_Fittipaldi.jpg',
    },
    {
      name: 'Niki Lauda',
      country: 'Austria',
      years: [1975, 1977, 1984],
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Lauda_at_1982_Dutch_Grand_Prix.jpg/349px-Lauda_at_1982_Dutch_Grand_Prix.jpg',
    },
    {
      name: 'James Hunt',
      country: 'Reino Unido',
      years: [1976],
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/James_Hunt_-_Dutch_GP_1976_crop_mod.jpg/480px-James_Hunt_-_Dutch_GP_1976_crop_mod.jpg',
    },
    {
      name: 'Mario Andretti',
      country: 'Estados Unidos',
      years: [1978],
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/MarioAndretti.jpg/316px-MarioAndretti.jpg',
    },
    {
      name: 'Jody Scheckter',
      country: 'Africa do Sul',
      years: [1979],
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Jody_Scheckter_during_the_1979_Monaco_Grand_Prix.jpg/336px-Jody_Scheckter_during_the_1979_Monaco_Grand_Prix.jpg',
    },
    {
      name: 'Alan Jones',
      country: 'Australia',
      years: [1980],
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Alan_Jones_%28racecar_driver%29.jpg/359px-Alan_Jones_%28racecar_driver%29.jpg',
    },
    {
      name: 'Nelson Piquet',
      country: 'Brasil',
      years: [1981, 1983, 1987],
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Cerimonia_de_entrega_da_medalha_Bras%C3%ADlia_60_anos_-_16.jpg/359px-Cerimonia_de_entrega_da_medalha_Bras%C3%ADlia_60_anos_-_16.jpg',
    },
    {
      name: 'Keke Rosberg',
      country: 'Finlândia',
      years: [1982],
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Anefo_932-2378_Keke_Rosberg%2C_Zandvoort%2C_03-07-1982.jpg/318px-Anefo_932-2378_Keke_Rosberg%2C_Zandvoort%2C_03-07-1982.jpg',
    },
    {
      name: 'Alan Prost',
      country: 'França',
      years: [1985, 1986, 1989, 1993],
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Alain_Prost_Cannes_2013.jpg/339px-Alain_Prost_Cannes_2013.jpg',
    },
    {
      name: 'Ayrton Senna',
      country: 'Brasil',
      years: [1988, 1990, 1991],
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Ayrton_Senna_8_%28cropped%29.jpg/371px-Ayrton_Senna_8_%28cropped%29.jpg',
    },
    {
      name: 'Nigel Mansell',
      country: 'Reino Unido',
      years: [1992],
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Nigel_Mansell_2007.jpg/480px-Nigel_Mansell_2007.jpg',
    },
    {
      name: 'Michael Schumacher',
      country: 'Alemanha',
      years: [1994, 1995, 2000, 2001, 2002, 2003, 2004],
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Michael_Schumacher_Berkedip_%28Cropped%29.jpg/393px-Michael_Schumacher_Berkedip_%28Cropped%29.jpg',
    },
    {
      name: 'Damon Hill',
      country: 'Reino Unido',
      years: [1996],
      img: 'https://upload.wikimedia.org/wikipedia/commons/e/ee/Damon_Hill_crop.jpg',
    },
    {
      name: 'Jacques Villeneuve',
      country: 'Canada',
      years: [1997],
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Jacques_Villeneuve_at_Mont-Tremblant_2010_01.jpg/384px-Jacques_Villeneuve_at_Mont-Tremblant_2010_01.jpg',
    },
    {
      name: 'Mika Häkkinen',
      country: 'Finlândia',
      years: [1998, 1999],
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/2016209185748_2016-07-27_Champions_for_Charity_-_Sven_-_1D_X_-_0226_-_DV3P4819_mod.jpg/319px-2016209185748_2016-07-27_Champions_for_Charity_-_Sven_-_1D_X_-_0226_-_DV3P4819_mod.jpg',
    },
    {
      name: 'Fernando Alonso',
      country: 'Espanha',
      years: [2005, 2006],
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Alonso_2016.jpg/384px-Alonso_2016.jpg',
    },
    {
      name: 'Kimi Räikkönen',
      country: 'Finlândia',
      years: [2007],
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/F12019_Schloss_Gabelhofen_%2822%29.jpg/320px-F12019_Schloss_Gabelhofen_%2822%29.jpg',
    },
    {
      name: 'Lewis Hamilton',
      country: 'Reino Unido',
      years: [2008, 2014, 2015, 2017, 2018, 2019, 2020],
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Sess%C3%A3o_Especial_-_T%C3%ADtulo_de_Cidad%C3%A3o_Honor%C3%A1rio_do_Brasil_%2852484885748%29_%28cropped%29.jpg/333px-Sess%C3%A3o_Especial_-_T%C3%ADtulo_de_Cidad%C3%A3o_Honor%C3%A1rio_do_Brasil_%2852484885748%29_%28cropped%29.jpg',
    },
    {
      name: 'Jenson Button',
      country: 'Reino Unido',
      years: [2009],
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Button_in_2018.JPG/359px-Button_in_2018.JPG',
    },
    {
      name: 'Sebastian Vettel',
      country: 'Alemanha',
      years: [2010, 2011, 2012, 2013],
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Sebastian_Vettel_2015_Malaysia_podium_1.jpg/320px-Sebastian_Vettel_2015_Malaysia_podium_1.jpg',
    },
    {
      name: 'Nico Rosberg',
      country: 'Alemanha',
      years: [2016],
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Nico_Rosberg_2016_Malaysia_1.jpg/320px-Nico_Rosberg_2016_Malaysia_1.jpg',
    },
    {
      name: 'Max Verstappen',
      country: 'Holanda',
      years: [2021, 2022],
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Max_Verstappen_2017_Malaysia_3.jpg/320px-Max_Verstappen_2017_Malaysia_3.jpg',
    },
  ]
};